# Generated by Django 5.1.4 on 2024-12-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twovrifi_secret',
            field=models.CharField(default='', max_length=90),
        ),
    ]
