# Generated by Django 5.1.4 on 2024-12-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_twovrifi_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twovrifi_secret',
        ),
    ]
